process = "C:/Windows/System32/notepad.exe"

recording = "Microphone (Gaming Headset)~{0.0.1.00000000}.{xx-yy-zz-123-098}"
recording_comms = "Microphone (Gaming Headset)~{0.0.1.00000000}.{xx-yy-zz-123-098}"
